name: ansi_logger
description: Flutter package tht help you make pretty logs
version: 2.0.0
homepage: https://github.com/mo-ah-dawood/ansi_logger
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies: 
dev_dependencies:
  test: ^1.16.3

