name: ansi_logger
description: Flutter package tht help you make pretty logs
version: 1.0.6
homepage: https://github.com/mo-ah-dawood/ansi_logger
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
